### ISSUE TITLE
Click areas in bookmark not clearly separated

### ISSUE THREAD

**Issue by Menti** [plainmade/unmark#114]
An image is better than an explanation:

![captura de pantalla de 2015-02-28 12 06 31](https://cloud.githubusercontent.com/assets/2584307/6425981/826d777e-bf42-11e4-8b60-bc7e020ee7a3.png)

The area within the dotted rectangle is an external link to the bookmarked page. It extends well past the end of the link text proper. There is no way to differentiate between this area and the outer area, where you click to see bookmark information (note, tags). So it's possible to click somewhere to open see the notes, and instead open a new tab with the bookmarked page.

Possible solutions:

- Different design for that area: for example background color.
- Make sure that the link area is limited to the space that the text occupies.

Thanks!

**Comment by cdevroe** [comment]
@Menti I understand your opinion. This area, though, has been painstakingly designed. And it isn't that we are not willing to make adjustments ... but perhaps we can explain the process here.

First, this area is also available on touch devices. We made the entire cell a tap, or click, so that you can see the notes. However, the URL and the title of the bookmark are both clickable/tappable to the bookmark. Also, when hovering in Unmark, you can see icons that allow you to see the notes.

Perhaps when I'm back on my computer (scrawling this out on my iPad currently) I can create a GIF to show how each piece interacts.

**Comment by cdevroe** [comment]
There is a PR #116 that addresses part of this issue. This will be rolled into the next release.
