### ISSUE TITLE
Containerize unmark?

### ISSUE THREAD

**Issue by SergiuCip** [plainmade/unmark#145]
Hello there,

The app is great but I am having a hard time setting up. I have done it once, but there's no users, even though I've created one at setup.

As many people including myself have found it difficult to install the application, wouldn't be good if someone who successfully installed the unmark could create a docker container?

Thanks and great app!

**Comment by cdevroe** [comment]
@SergiuCip I agree. _Something_ has to happen to make it easier to install. I'm not sure if adding more dependencies (like knowing what Docker is) is the answer. But _something_ should be done.

One thing that could help is the recent PR #153 which fixes a few issues people have had just after setting up. Next will be to continue to chip away at issues inherent with CodeIgniter applications at set up.

**Comment by moltenkaizen** [comment]
Another vote here. A container would be handy. I've spent all day trying to set this up

**Comment by virtadpt** [comment]
Unmark is a PHP application.  Running it inside a container isn't going to get you much because you'll have to install Apache, PHP, MySQL, and everthing else inside it, and in the final analysis all of the .php files are going to be executed server-side inside of the PHP interpreter.  If unmark was a node.js or a Rails application, that would make sense.

Did you try installing Unmark inside of a subdirectory of an existing website, by chance?

**Comment by cdevroe** [comment]
@virtadpt I think @moltenkaizen has solved his issues using the latest release.

And though containerizing Unmark would make some sense because all dependencies could be wrapped up in a box... I think the better use of our time (read: mostly my time) will be to remove the dependencies. The last biggie is gettext which I plan on removing ASAP.
