### ISSUE TITLE
Please officially document the import JSON document format.

### ISSUE THREAD

**Issue by virtadpt** [plainmade/unmark#148]
Hi.  Please write canonical documentation for the JSON document import format.  I've spent the last couple of days writing a Netscape bookmarks-to-JSON converter, without much success.  Some of the fields are self-explanatory, but others (tags: {}) don't seem to make sense (shouldn't tags be a list and not an object?)

At the very least it'll make things significantly easier for those of us who are trying to get away from certain services that only export in HTML format.

**Comment by Kovah** [comment]
I could need some more information about that too. Wrote a Python script to convert my Del.icio.us bookmarks but not a single generated JSON file was accepted. The closest I could get was this by using the export file itself but added some (~15) own marks.
![screen shot 2016-09-06 at 14 53 22](https://cloud.githubusercontent.com/assets/1816101/18274225/b41dd16e-7441-11e6-8d1f-74ce0802a228.png)

**Comment by cdevroe** [comment]
@virtadpt @Kovah I will try to get to this this week.

**Comment by cdevroe** [comment]
@Kovah I'm doing this now. 

More importantly, I will document Unmark's _Export_ JSON format as it should be thought of (at this point at least) as more of a "backup" of someone's Unmark install rather than an export/import schema.

However, I'll write up a doc so we all understand the JSON schema. 

To import from Delicious, though, you could do what I did over on #158 to import Readability -- which is -- add new import functionality. I'd love to see Unmark support more services.

**Comment by cdevroe** [comment]
@virtadpt @Kovah Please see branch:148-export-schema

Here is the document: https://github.com/plainmade/unmark/blob/148-export-schema/export-schema.md

I will roll this in when we get PRs #157 & #158 rolled in.
