### ISSUE TITLE
Cannot bookmark certain urls using the bookmarklet

### ISSUE THREAD

**Issue by weaktyper** [plainmade/unmark#201]
I cannot bookmark certain urls using the bookmarklet, for example, I cannot bookmark the following url, nothing happens when clicked:
`https://github.com/plainmade/unmark/issues`.

Is there some mod for the bookmarklet to overcome this or am i missing something?

**Comment by virtadpt** [comment]
I run into this all the time, mostly involving Github URLs but also on Twitter.  It's an annoying enough problem that I have a sticky note on my desktop with a shortcut URL that I use as a workaround.

**Comment by weaktyper** [comment]
@virtadpt 
How does your solution work? Do you have some self-hosted shortcut url generator and you generate your ony tinyurl?

Also, is there some way I can look into a technical solution for this? Where should I look in the source code?

**Comment by virtadpt** [comment]
I edited the bookmarklet and copied it into an online URL encoder/decoder.  I then extracted the exact URL the bookmarklet uses to add links to Unmark.  In my case, it looks like this:

http://unmark.myserver.example.com/mark/add?url=+

I keep that URL in a stickynote on my desktop, and whenever I run into a website that doesn't work with the bookmarklet (mostly Github) I open a new browser tab, copy that URL into the address bar, and append the URL I want to add to Unmark to the URL.  When I hit enter I get the Unmark "add a link and add notes to it" page (instead of a little popup window containing same) and save the link.

This is not a good workflow.

**Comment by weaktyper** [comment]
thanks for this tip, this works ok.
I made a slight enhancement to the workflow which was to make a bookmark with location `https://unmark.codinghere.com/mark/add?url=+` and then simply append the previous hyperlink. Almost the same as what you do except I don't need the sticky note.
