### ISSUE TITLE
/setup error "Unable to select database"

### ISSUE THREAD

**Issue by szmarci** [plainmade/unmark#56]
I'm trying to setup unmark on my localhost machine, but for some reason it is not working.
I create the database, I fill out the data in `database.php` but I keep getting this:
AN UNEXPECTED ERROR HAS OCCURED The issue has been logged and will be taken care of shortly.

I checked the logs, it is full of this:
ERROR - 2014-07-22 16:35:59 --> Unable to select database: bookmark
(bookmark is the name of the database).

I have no idea what is wrong.
MySQL is version 5.6.19
PHP is 5.4.24
System is Mac OS X 10.9.3

**Comment by williamknauss** [comment]
@szmarci,
I'm sorry your having trouble getting Unmark installed. Lets see what I can do to help out. 
I see you mentioned creating a user through Sequal Pro. While it doesn't matter what program or system is used to create the user, the user does need some rights in order to successfully install Unmark.

While I can't seem to find documentation stating what SQL rights are needed, I suggest giving your user all rights to the bookmarks database exepect "GRANT OPTION".

Let me know if this helps.

**Comment by williamknauss** [comment]
Hi @szmarci,
Try downloading the newest [master branch] (https://github.com/plainmade/unmark/archive/master.zip). Unmark has made great progress in being more verbose about errors. 

Feel free to open a new issue if you still encounter issues.

Thanks Mate@
