### ISSUE TITLE
environment constant logic

### ISSUE THREAD

**Issue by williamknauss** [plainmade/unmark#89]
If I could create labels I would put "logic" on this issue.

I would say the logic to determine the "ENVIRONMENT" is well a bit jumbled.

First you check to see if an application configuration file exists (environment.php), then you check UNMARK_ENV_CONFIG_GLOBAL constant (path), and if ENVIRONMENT is still not set you default it to "production".

Would it be to bold to suggest to drop all of the logic and replace it with something simpler, maybe something along these lines:
```php
if (isset($_SERVER['UNMARK_ENV_PATH'])) {
    if (is_readable($_SERVER['UNMARK_ENV_PATH'])) {
        include_once($_SERVER['UNMARK_ENV_PATH']);
    }
}


if (!defined('ENVIRONMENT')) {
   define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'production');
}
```

A solution like this would provide cleaner code and still grant the flexibility of having 1 configuration file shared among many different installs. (In direct reference to /etc/unmark/environment.php)

Thoughts, ideas, feedback?

**Comment by cdevroe** [comment]
I think we can ditch all of this logic to help make the open source version of Unmark much, much easier. We can even ditch the environment constant since I seriously doubt many people are running Unmark in multiple environments. That was specifically for unmark.it and I'm more than willing to ditch all of this extra stuff for simplicities sake.

I say we rip it.

**Comment by williamknauss** [comment]
Fair enough lets rip it out!!! WOOT! :put_litter_in_its_place:
